name: Download File
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - name: Install download tool
      run: dotnet tool install -g dotnetCampus.FileDownloader.Tool
    - name: Install send mail tool
      run: dotnet tool install -g dotnetCampus.SendEmailTask
 
    - name: Download File
      run: DownloadFile -u https://gsdview.appspot.com/chromium-browser-official/chromium-99.0.4844.84.tar.xz -o file.zip
    - name: Send file
      run: SendEmail -t liheyuandownfile@yandex.com -s "SendFile" -b "File" --Files file.zip --SmtpServer smtp.yandex.com --SmtpServerPort 587 --UserName liheyuandownfile@yandex.com --Password miBN8dFLxdUs9d3